public enum TK {
    IF, ELSE, WHILE, RETURN, INT, FLOAT, CHAR, BOOLEAN, VOID, TRUE, FALSE, NULL,
    LPAREN, RPAREN, LBRACE, RBRACE, LBRACK, RBRACK, SEMICOLON, COMMA, DOT,
    IDENTIFIER, TYPE_NAME, INTEGER_LITERAL, FLOATING_POINT_LITERAL,
    CHARACTER_LITERAL, STRING_LITERAL, OPERATOR, DOUBLE_COLON, COLON, EOF,OPEN_COMMENT
}