name: CI

on:
  push:
    branches:
      - tp-02

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
          
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
        
    - name: Install Make
      run: sudo apt-get install -y make
      
    - name: Check for .class files
      id: class_check
      run: |
        cd src/
        if find . -name "*.class" | read
        then
          echo "has_class_files=true" >> $GITHUB_OUTPUT
        else
          echo "has_class_files=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Clean and build
      run: |
        cd src/
        if ${{ steps.class_check.outputs.has_class_files }}; then
          make clean
        fi
        make
        
    - name: Run Java Compiler
      id: java_compiler
      run: |
        cd src/
        output=$(java Demo ../arquivos_de_teste/pessoal.lan)
        echo "compiler_output<<EOF" >> $GITHUB_OUTPUT
        echo "$output" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    
    - name: Display Compiler Output
      run: |
        echo "Compiler Output:"
        echo "${{ steps.java_compiler.outputs.compiler_output }}"

    - name: Making a zip
      uses: TheDoctor0/zip-release@0.7.6
      with:
        # Filename for archive
        filename: release.zip
        # Base path for archive files
        path: .
           
    - name: Upload Release
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: release.zip
        path: release.zip
