name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
          
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
        
    - name: Install Make
      run: sudo apt-get install -y make
      
    - name: Check for .class files
      id: class_check
      run: |
        cd src/
        if find . -name "*.class" | read
        then
          echo "has_class_files=true" >> $GITHUB_OUTPUT
        else
          echo "has_class_files=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Clean and build
      run: |
        cd src/
        if ${{ steps.class_check.outputs.has_class_files }}; then
          make clean
        fi
        make
        
    - name: Run Java Compiler
      id: java_compiler
      run: |
        cd src/
        output=$(java Compiler ../arquivos_de_teste/data.lan)
        echo "compiler_output<<EOF" >> $GITHUB_OUTPUT
        echo "$output" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    
    - name: Display Compiler Output
      run: |
        echo "Compiler Output:"
        echo "${{ steps.java_compiler.outputs.compiler_output }}"
    - name: Create Release ZIP
      if: success()
      run: |
        CURRENT_DATE=$(date +"%d-%m-%Y")
        zip -r release-$CURRENT_DATE.zip .
            
    - name: Upload Release
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: release-${{ steps.java_compiler.outputs.compiler_output }}-$CURRENT_DATE
        path: release-$CURRENT_DATE.zip
